#!/usr/bin/env python3
"""Extract deal notes from a text file and write them into deal folders."""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass, field
from datetime import datetime
from difflib import SequenceMatcher
from pathlib import Path

from dotenv import load_dotenv

from consolidator import list_candidate_note_files
from document_utils import read_file_as_text
from fetch_all_transcripts import (
    DealCatalogEntry,
    catalog_targets,
    load_deal_catalog,
    resolve_catalog_entry,
)
from fetch_transcripts import (
    MatchResult,
    groq_json_chat,
    shortlist_deal_matches_from_haystack,
)
from paths import deals_base

DEFAULT_MODEL = "openai/gpt-oss-120b"
NOTE_FILENAME_PREFIX = "note_"
NOTE_BODY_DATETIME_FMT = "%Y-%m-%d %H:%M:%S"
VALID_KINDS = ("decision", "opinion", "action")
VALID_KIND_SET = frozenset(VALID_KINDS)
INPUT_MAX_CHARS = 80_000
EXISTING_NOTES_CHARS = 8_000
SUMMARY_CHARS = 2_000
AI_FOOTER = "(This note was generated by AI.)"
NEAR_MATCH_CUTOFF = 0.8
MIN_NEAR_MATCH_LEN = 6

EXTRACT_FACTS_SYSTEM_PROMPT = """You extract durable internal facts from Antler team text.

Return valid JSON only with this exact shape:
{
  "facts": [
    {
      "company_hint": "name as written in the text",
      "kind": "decision",
      "content": "concise third-person sentence"
    }
  ]
}

kind must be exactly one of: decision, opinion, action.

Rules:
- Only extract decisions, opinions, or actions about a specific startup/deal.
- company_hint is the company or deal name as it appears in the text, not a guessed folder name.
- content is one concise third-person sentence (e.g. "Tammer has decided that he will pass on Clovie.").
- Do not invent facts. If the input is a simple instruction, extract that instruction as a fact.
- Skip play-by-play discussion, greetings, and logistics with no decision/opinion/action.
- These Antler team members are the investing team (not companies): Tammer Kamel, Shambhavi Mishra, Alex Wright, Daphne McLarty, Bernie Li, Matt.
- facts may be an empty list if there is nothing to extract.
"""

NET_NEW_SYSTEM_PROMPT = """You decide whether proposed deal notes add information not already recorded.

Return valid JSON only with this exact shape:
{
  "results": [
    {
      "deal_folder": "FolderName",
      "keep": true,
      "reason": "short explanation",
      "content": "note text to write"
    }
  ]
}

The proposed note is Antler team source material. Treat it as factual and accurate. Do not judge whether it is true, consistent, or well spelled.

Keep a note when it adds a decision, opinion, action, or status that is not already recorded for that deal.
Keep a note when it contradicts existing notes or the summary — a contradiction is new information and MUST be written.
Set keep=false ONLY when the proposed note restates the same already-recorded fact with no material addition.

Do not reject a note because:
- the company name is spelled differently from the folder (e.g. Lightgood vs Lightgrid)
- it disagrees with prior notes or summary.md
- you think the information is inaccurate or outdated

If keep=true, content should be the note text to write. You may lightly copy-edit and you may replace a misspelled company name with the deal folder's canonical name. Do not invent facts and do not drop substance.
If keep=false, content may be empty.
reason must be one concise sentence.
Evaluate every proposed note. deal_folder must match the input exactly.
"""

NEAR_MATCH_SYSTEM_PROMPT = """You match a company name that did not exactly match any deal folder.

You are given the unmatched name and a catalog of deal folders (folder name, company, aliases).

Return valid JSON only with this exact shape:
{"deal_folder": "FolderName" or null, "matched_name": "catalog name that is close" or null, "reason": "short explanation"}

Rules:
- Return a deal_folder ONLY when the unmatched name is clearly the same company with a typo, misspelling, spacing, or minor variant (e.g. Lightgood Energy → Lightgrid Energy).
- deal_folder must be an exact catalog folder name string, or null.
- matched_name is the catalog folder/company/alias you matched, or null.
- If no catalog entry is a likely typo/variant, return null.
- If two or more catalog entries are equally plausible, return null.
- Do not match on shared generic words alone (Energy, Labs, AI, Health).
- Do not match unrelated similar-sounding companies.
- reason must be one concise sentence.
"""


@dataclass(frozen=True)
class ExtractedFact:
    company_hint: str
    kind: str
    content: str


@dataclass
class ProposedNote:
    deal_folder: str
    folder: Path
    kinds: list[str] = field(default_factory=list)
    content: str = ""
    hints: list[str] = field(default_factory=list)
    match_reason: str = ""


@dataclass
class NoteOutcome:
    status: str
    deal_folder: str | None = None
    filename: str | None = None
    kinds: list[str] = field(default_factory=list)
    content: str = ""
    reason: str = ""
    company_hint: str | None = None


def note_filename(when: datetime) -> str:
    return f"{NOTE_FILENAME_PREFIX}{when.strftime('%Y%m%d_%H%M%S')}.txt"


def format_note_body(when: datetime, content: str) -> str:
    stamp = when.strftime(NOTE_BODY_DATETIME_FMT)
    text = content.strip()
    return f"{stamp}\n\n{text}\n\n{AI_FOOTER}\n"


def format_kinds(kinds: list[str]) -> str:
    return ", ".join(dict.fromkeys(kinds))


def deal_match_names(deal: DealCatalogEntry) -> list[str]:
    names: list[str] = []
    seen: set[str] = set()
    for raw in (
        deal.folder_name,
        deal.identity.company_name,
        *deal.identity.aliases,
    ):
        if not raw:
            continue
        cleaned = raw.strip()
        key = cleaned.lower()
        if not cleaned or key in seen:
            continue
        seen.add(key)
        names.append(cleaned)
    return names


def format_catalog_names_for_prompt(catalog: list[DealCatalogEntry]) -> str:
    lines: list[str] = []
    for deal in catalog:
        aliases = ", ".join(deal.identity.aliases) or "(none)"
        company = deal.identity.company_name or "(none)"
        lines.append(
            f"- folder: {deal.folder_name}; company: {company}; aliases: {aliases}"
        )
    return "\n".join(lines)


def difflib_near_folder_matches(
    hint: str,
    catalog: list[DealCatalogEntry],
    *,
    cutoff: float = NEAR_MATCH_CUTOFF,
) -> list[tuple[DealCatalogEntry, str, float]]:
    needle = hint.strip().lower()
    best_by_folder: dict[str, tuple[DealCatalogEntry, str, float]] = {}
    for deal in catalog:
        for name in deal_match_names(deal):
            ratio = SequenceMatcher(None, needle, name.lower()).ratio()
            if ratio < cutoff:
                continue
            previous = best_by_folder.get(deal.folder_name)
            if previous is None or ratio > previous[2]:
                best_by_folder[deal.folder_name] = (deal, name, ratio)
    return sorted(best_by_folder.values(), key=lambda item: item[2], reverse=True)


def groq_near_match(
    hint: str,
    catalog: list[DealCatalogEntry],
    *,
    api_key: str,
    model: str,
) -> MatchResult:
    if not catalog:
        return MatchResult(
            deal_folder=None,
            reason=f"no deal folder found for {hint!r}. Did nothing.",
        )

    payload = groq_json_chat(
        system_prompt=NEAR_MATCH_SYSTEM_PROMPT,
        user_prompt=(
            f"Unmatched name: {hint}\n\n"
            "Deal catalog:\n"
            f"{format_catalog_names_for_prompt(catalog)}"
        ),
        api_key=api_key,
        model=model,
    )
    if not isinstance(payload, dict):
        return MatchResult(
            deal_folder=None,
            reason=f"no deal folder found for {hint!r}. Did nothing.",
        )

    deal_folder_raw = payload.get("deal_folder")
    deal_folder = str(deal_folder_raw).strip() if deal_folder_raw else ""
    if not deal_folder or deal_folder.lower() in {"null", "none"}:
        reason = str(payload.get("reason", "")).strip()
        return MatchResult(
            deal_folder=None,
            reason=reason or f"no deal folder found for {hint!r}. Did nothing.",
        )

    entry = resolve_catalog_entry(catalog, deal_folder)
    if entry is None:
        return MatchResult(
            deal_folder=None,
            reason=f"ambiguous or unknown near-match {deal_folder!r}. Did nothing.",
        )

    matched_name = str(payload.get("matched_name", "")).strip() or entry.folder_name
    return MatchResult(
        deal_folder=entry.folder_name,
        reason=(
            f"Matched {entry.folder_name} by near-name {hint!r} → {matched_name!r}."
        ),
    )


def exact_folder_matches(
    hint: str,
    catalog: list[DealCatalogEntry],
) -> list[DealCatalogEntry]:
    needle = hint.strip().lower()
    if not needle:
        return []

    matches: list[DealCatalogEntry] = []
    seen: set[str] = set()
    for deal in catalog:
        names = [deal.folder_name]
        if deal.identity.company_name:
            names.append(deal.identity.company_name)
        if any(name.strip().lower() == needle for name in names):
            if deal.folder_name not in seen:
                matches.append(deal)
                seen.add(deal.folder_name)
    return matches


def match_hint_to_folder(
    hint: str,
    catalog: list[DealCatalogEntry],
    *,
    api_key: str | None = None,
    model: str | None = None,
) -> MatchResult:
    cleaned = hint.strip()
    if not cleaned:
        return MatchResult(
            deal_folder=None,
            reason="empty company hint. Did nothing.",
        )

    exact = exact_folder_matches(cleaned, catalog)
    if len(exact) == 1:
        folder_name = exact[0].folder_name
        return MatchResult(
            deal_folder=folder_name,
            reason=f"Matched {folder_name} by exact name {cleaned!r}.",
        )
    if len(exact) > 1:
        names = ", ".join(deal.folder_name for deal in exact)
        return MatchResult(
            deal_folder=None,
            reason=f"ambiguous ({names}). Did nothing.",
        )

    targets = catalog_targets(catalog)
    candidates = shortlist_deal_matches_from_haystack(
        cleaned,
        targets,
        limit=len(targets) or 1,
    )
    strong = [candidate for candidate in candidates if candidate.strong_hits > 0]
    if len(strong) == 1:
        winner = strong[0]
        detail = ", ".join(winner.reasons) or "strong signal"
        return MatchResult(
            deal_folder=winner.folder_name,
            reason=f"Matched {winner.folder_name} by {detail} in company hint.",
        )
    if len(strong) > 1:
        names = ", ".join(candidate.folder_name for candidate in strong)
        return MatchResult(
            deal_folder=None,
            reason=f"ambiguous ({names}). Did nothing.",
        )

    close: list[tuple[DealCatalogEntry, str, float]] = []
    if len(cleaned) >= MIN_NEAR_MATCH_LEN:
        close = difflib_near_folder_matches(cleaned, catalog)
        if len(close) == 1:
            deal, name, _ratio = close[0]
            return MatchResult(
                deal_folder=deal.folder_name,
                reason=(
                    f"Matched {deal.folder_name} by near-name {cleaned!r} → {name!r}."
                ),
            )

    if api_key and len(cleaned) >= MIN_NEAR_MATCH_LEN:
        groq_catalog = [deal for deal, _name, _ratio in close] if close else catalog
        return groq_near_match(
            cleaned,
            groq_catalog,
            api_key=api_key,
            model=model or DEFAULT_MODEL,
        )

    if len(close) > 1:
        names = ", ".join(deal.folder_name for deal, _name, _ratio in close)
        return MatchResult(
            deal_folder=None,
            reason=f"ambiguous ({names}). Did nothing.",
        )
    return MatchResult(
        deal_folder=None,
        reason=f"no deal folder found for {cleaned!r}. Did nothing.",
    )


def parse_extracted_facts(payload: object) -> list[ExtractedFact]:
    if not isinstance(payload, dict):
        return []
    raw_facts = payload.get("facts", [])
    if not isinstance(raw_facts, list):
        return []

    facts: list[ExtractedFact] = []
    for item in raw_facts:
        if not isinstance(item, dict):
            continue
        hint = str(item.get("company_hint", "")).strip()
        kind = str(item.get("kind", "")).strip().lower()
        content = str(item.get("content", "")).strip()
        if not hint or not content or kind not in VALID_KIND_SET:
            continue
        facts.append(ExtractedFact(company_hint=hint, kind=kind, content=content))
    return facts


def extract_facts(
    text: str,
    *,
    api_key: str,
    model: str,
) -> list[ExtractedFact]:
    payload = groq_json_chat(
        system_prompt=EXTRACT_FACTS_SYSTEM_PROMPT,
        user_prompt=f"Document content:\n{text}",
        api_key=api_key,
        model=model,
    )
    return parse_extracted_facts(payload)


def collapse_facts_by_deal(
    matched: list[tuple[ExtractedFact, DealCatalogEntry, str]],
) -> list[ProposedNote]:
    grouped: dict[str, ProposedNote] = {}
    for fact, entry, match_reason in matched:
        existing = grouped.get(entry.folder_name)
        if existing is None:
            grouped[entry.folder_name] = ProposedNote(
                deal_folder=entry.folder_name,
                folder=entry.folder,
                kinds=[fact.kind],
                content=fact.content,
                hints=[fact.company_hint],
                match_reason=match_reason,
            )
            continue
        existing.kinds.append(fact.kind)
        existing.content = f"{existing.content}\n\n{fact.content}"
        existing.hints.append(fact.company_hint)
    return list(grouped.values())


def load_existing_context(folder: Path) -> str:
    parts: list[str] = []
    if folder.is_dir():
        note_chunks: list[str] = []
        for path in list_candidate_note_files(folder):
            text = read_file_as_text(path)
            if not text or not text.strip():
                continue
            note_chunks.append(f"### {path.name}\n{text.strip()}")
        notes = "\n\n".join(note_chunks)
        if len(notes) > EXISTING_NOTES_CHARS:
            notes = notes[:EXISTING_NOTES_CHARS] + "\n\n[truncated]"
        if notes:
            parts.append("Existing notes:\n" + notes)

    summary_path = folder / "ai-generated" / "summary.md"
    if summary_path.is_file():
        summary = read_file_as_text(summary_path) or ""
        summary = summary.strip()
        if len(summary) > SUMMARY_CHARS:
            summary = summary[:SUMMARY_CHARS] + "\n\n[truncated]"
        if summary:
            parts.append("Existing summary.md:\n" + summary)

    return "\n\n".join(parts)


def build_net_new_prompt(notes: list[ProposedNote]) -> str:
    blocks: list[str] = []
    for note in notes:
        existing = load_existing_context(note.folder) or "(none)"
        hints = ", ".join(dict.fromkeys(note.hints)) or "(none)"
        blocks.append(
            f"## Deal folder: {note.deal_folder}\n"
            f"Kind: {format_kinds(note.kinds)}\n"
            f"Name as given in the source (treat as this deal): {hints}\n"
            f"Proposed note:\n{note.content}\n\n"
            f"{existing}"
        )
    return (
        "Proposed notes to evaluate. Treat each proposed note as factual. "
        "Skip only exact restatements of already-recorded facts. "
        "Contradictions and spelling variants of the deal name are not reasons to skip.\n\n"
        + "\n\n".join(blocks)
    )


def parse_net_new_results(payload: object) -> dict[str, tuple[bool, str, str]]:
    results: dict[str, tuple[bool, str, str]] = {}
    if not isinstance(payload, dict):
        return results
    raw = payload.get("results", [])
    if not isinstance(raw, list):
        return results
    for item in raw:
        if not isinstance(item, dict):
            continue
        folder = str(item.get("deal_folder", "")).strip()
        if not folder:
            continue
        keep = bool(item.get("keep", False))
        reason = str(item.get("reason", "")).strip()
        content = str(item.get("content", "")).strip()
        results[folder] = (keep, reason, content)
    return results


def filter_net_new(
    notes: list[ProposedNote],
    *,
    api_key: str,
    model: str,
) -> tuple[list[ProposedNote], list[NoteOutcome]]:
    if not notes:
        return [], []

    needs_check: list[ProposedNote] = []
    skip_check: list[ProposedNote] = []
    for note in notes:
        if load_existing_context(note.folder):
            needs_check.append(note)
        else:
            skip_check.append(note)
    if not needs_check:
        return notes, []

    payload = groq_json_chat(
        system_prompt=NET_NEW_SYSTEM_PROMPT,
        user_prompt=build_net_new_prompt(needs_check),
        api_key=api_key,
        model=model,
    )
    parsed = parse_net_new_results(payload)

    kept: list[ProposedNote] = list(skip_check)
    skipped: list[NoteOutcome] = []
    for note in needs_check:
        decision = parsed.get(note.deal_folder)
        if decision is None:
            kept.append(note)
            continue
        keep, reason, content = decision
        if not keep:
            skipped.append(
                NoteOutcome(
                    status="skipped",
                    deal_folder=note.deal_folder,
                    kinds=list(note.kinds),
                    content=note.content,
                    reason=reason or "not net new. Did nothing.",
                    company_hint=note.hints[0] if note.hints else None,
                )
            )
            continue
        if content:
            note.content = content
        kept.append(note)
    return kept, skipped


def write_deal_note(
    folder: Path,
    filename: str,
    body: str,
    *,
    dry_run: bool,
) -> str:
    path = folder / filename
    if path.exists():
        return "skipped"
    if dry_run:
        return "would_write"
    path.write_text(body, encoding="utf-8")
    return "written"


def print_outcome(outcome: NoteOutcome) -> None:
    if outcome.status in {"written", "would_write"}:
        label = "WROTE" if outcome.status == "written" else "WOULD WRITE"
        print(f"{label}: {outcome.deal_folder}/{outcome.filename}")
        if outcome.kinds:
            print(f"  Kind: {format_kinds(outcome.kinds)}")
        if outcome.content:
            for line in outcome.content.splitlines():
                print(f"  {line}" if line else "")
        if outcome.reason:
            print(f"  Reason: {outcome.reason}")
        return

    if outcome.status == "skipped":
        print(f"SKIPPED: {outcome.deal_folder or outcome.company_hint or '(unknown)'}")
        if outcome.reason:
            print(f"  Reason: {outcome.reason}")
        return

    if outcome.status == "no_match":
        hint = outcome.company_hint or "(unknown)"
        print(f"NO MATCH: {hint!r}")
        if outcome.reason:
            print(f"  Reason: {outcome.reason}")
        return

    print(f"ERROR: {outcome.deal_folder or outcome.company_hint or '(unknown)'}")
    if outcome.reason:
        print(f"  Reason: {outcome.reason}")


def read_input_text(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"input file does not exist: {path}")
    if not path.is_file():
        raise ValueError(f"input path is not a file: {path}")
    text = read_file_as_text(path)
    if text is None:
        raise ValueError(f"could not read input as text: {path}")
    stripped = text.strip()
    if not stripped:
        raise ValueError(f"input file is empty: {path}")
    if len(stripped) > INPUT_MAX_CHARS:
        print(
            f"Warning: input truncated from {len(stripped)} to {INPUT_MAX_CHARS} characters",
            file=sys.stderr,
        )
        return stripped[:INPUT_MAX_CHARS]
    return stripped


def create_notes_from_text(
    text: str,
    catalog: list[DealCatalogEntry],
    *,
    api_key: str,
    model: str,
    dry_run: bool,
    now: datetime | None = None,
) -> list[NoteOutcome]:
    when = now or datetime.now()
    filename = note_filename(when)
    outcomes: list[NoteOutcome] = []

    facts = extract_facts(text, api_key=api_key, model=model)
    if not facts:
        return outcomes

    matched: list[tuple[ExtractedFact, DealCatalogEntry, str]] = []
    for fact in facts:
        match = match_hint_to_folder(
            fact.company_hint,
            catalog,
            api_key=api_key,
            model=model,
        )
        if not match.deal_folder:
            outcomes.append(
                NoteOutcome(
                    status="no_match",
                    company_hint=fact.company_hint,
                    kinds=[fact.kind],
                    content=fact.content,
                    reason=match.reason,
                )
            )
            continue
        entry = resolve_catalog_entry(catalog, match.deal_folder)
        if entry is None:
            outcomes.append(
                NoteOutcome(
                    status="no_match",
                    company_hint=fact.company_hint,
                    kinds=[fact.kind],
                    content=fact.content,
                    reason=(
                        f"Model returned unknown deal folder: "
                        f"{match.deal_folder}. Did nothing."
                    ),
                )
            )
            continue
        matched.append((fact, entry, match.reason))

    proposed = collapse_facts_by_deal(matched)
    kept, skipped = filter_net_new(
        proposed,
        api_key=api_key,
        model=model,
    )
    outcomes.extend(skipped)

    for note in kept:
        body = format_note_body(when, note.content)
        status = write_deal_note(
            note.folder,
            filename,
            body,
            dry_run=dry_run,
        )
        reason = note.match_reason
        if status == "skipped":
            reason = f"{note.folder / filename} already exists. Did nothing."
        outcomes.append(
            NoteOutcome(
                status=status,
                deal_folder=note.deal_folder,
                filename=filename,
                kinds=list(note.kinds),
                content=note.content,
                reason=reason,
                company_hint=note.hints[0] if note.hints else None,
            )
        )
    return outcomes


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Read a text file, extract net-new deal decisions/opinions/actions, "
            "and write a timestamped note into each uniquely matched deal folder."
        )
    )
    parser.add_argument(
        "input_file",
        help="Path to a transcript, instruction, or other text file",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report notes without writing files.",
    )
    parser.add_argument(
        "--refresh-identity",
        action="store_true",
        help="Force rebuild of ai-generated/identity.json for all deal folders.",
    )
    return parser.parse_args()


def main() -> int:
    load_dotenv()
    args = parse_args()

    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        print("Error: GROQ_API_KEY is not set", file=sys.stderr)
        return 1
    model = os.getenv("GROQ_MODEL", DEFAULT_MODEL)

    try:
        text = read_input_text(Path(args.input_file).expanduser())
    except (OSError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    try:
        base = deals_base()
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    if not base.exists() or not base.is_dir():
        print(f"Error: deals base is not a directory: {base}", file=sys.stderr)
        return 1

    try:
        catalog = load_deal_catalog(
            base,
            api_key=api_key,
            model=model,
            refresh_identity=args.refresh_identity,
        )
    except Exception as exc:
        print(f"Error: failed to load deal catalog: {exc}", file=sys.stderr)
        return 1

    if not catalog:
        print("Error: no deal folders found", file=sys.stderr)
        return 1

    try:
        outcomes = create_notes_from_text(
            text,
            catalog,
            api_key=api_key,
            model=model,
            dry_run=args.dry_run,
        )
    except Exception as exc:
        print(f"Error: failed to create notes: {exc}", file=sys.stderr)
        return 1

    if not outcomes:
        print("Did nothing. No notes generated.")
        print("  Reason: no decisions, opinions, or actions found.")
        return 0

    for outcome in outcomes:
        print_outcome(outcome)

    produced = sum(
        1 for outcome in outcomes if outcome.status in {"written", "would_write"}
    )
    if produced == 0:
        print()
        print("Did nothing. No notes generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
