#!/usr/bin/env python3
"""Generate Claude-backed metadata for a single file under GOOGLE_DRIVE_BASE."""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, TypedDict

from anthropic import Anthropic
from dotenv import load_dotenv

from claude_common import MODEL, estimate_cost, extract_response_text
from consolidator import (
    ALLOWED_AUTHORS,
    AUTHOR_ALIASES,
    DATETIME_FMT,
    file_mtime,
    resolve_entry_datetime,
)
from document_utils import read_file_as_text
from get_facts import parse_json_response

DEFAULT_MODEL = MODEL
MAX_OUTPUT_TOKENS = 8192

SYSTEM_PROMPT = """You analyze a single document and return metadata as JSON.

Return valid JSON only with this exact shape:
{
  "creator": "Tammer",
  "created_at": "2026-01-01 12:00:00",
  "file_type": "what is the nature of the file?"
  "short summary": "brief summary of the document",
  "full summary": "fuller summary capturing the meaning of the document",
  "URL": "a URL for the file if one is available. else null."
}

## creator

Must be exactly one of: Tammer, Bernie, Shambhavi, Alex, Matt, Daphne, other, unknown.

- Map initials/full names: TK/Tammer Kamel→Tammer, BL/Bernie Li→Bernie,
  SM/Shambhavi Mishra→Shambhavi, AW/Alex Wright→Alex, DM/Daphne McLarty→Daphne, Matt→Matt.
- Infer creator from document text or filename when clear.
- If you can determine a creator but they are not in the named list, use "other".
- If you cannot determine the creator, use "unknown".

## created_at

Must be "YYYY-MM-DD HH:MM:SS" when a clear date is available, otherwise the string "unknown".
Sources for created_at, in order:
1. An explicit date in the document text (e.g. "2026-07-14", "July 14, 2026", "July 14th", "Jul 20").
2. A timestamp or date embedded in the filename (the Filename field is provided for this).
If neither the document nor the filename gives a clear date, set created_at to "unknown".
If a date has a month/day but no year, assume the current year (provided in the user message).
If only a date is known and no time, use 00:00:00.

## file_type

Determine the nature of the file. CHoose from:

internal note: use this if is appears to be a note or comment made by a team member.
email: choose this if the file appears to be an email.
transcript: choose this if the file appears to be a transcript of a conversation.
facts: choose this if the file appears to be nothing but facts without any commentary
founder generated: choose this if the file appears to be a document generated by the founder such as a pitch deck, proposal, or other documuemnt you might find in their data room.


## summaries

- short summary: ~100 words or less; capture the gist.
- full summary: as long as necessary to capture the meaning; do not invent facts. always include all email addresses mentioned, all linkedin urls mentioned, any phone numbers mentioned. all critical facts and numbers must be included.

## URL

check if the text contains a URL. if so, use it. if not say "no URL found".
transcipts usually have a url to a meetgeek link. if that is there, use it.

"""




class ClaudeStats(TypedDict):
    input_tokens: int
    output_tokens: int
    cost_usd: float | None
    model: str


MetadataResult = TypedDict(
    "MetadataResult",
    {
        "filename": str,
        "creator": str,
        "created_at": str,
        "timestamp": str,
        "short summary": str,
        "full summary": str,
        "claude_stats": ClaudeStats,
    },
)


def resolve_file_path(relative_path: str) -> Path:
    base_raw = os.getenv("GOOGLE_DRIVE_BASE")
    if not base_raw:
        raise ValueError("GOOGLE_DRIVE_BASE is not set")
    base = Path(base_raw).resolve()
    path = (base / relative_path.lstrip("/")).resolve()

    if base not in path.parents and path != base:
        raise ValueError(f"path escapes Google Drive root: {relative_path}")

    return path


def normalize_creator(value: object) -> str:
    if not isinstance(value, str):
        return "unknown"
    cleaned = value.strip()
    if not cleaned:
        return "unknown"
    lowered = cleaned.lower()
    if lowered in {"unknown", "none", "null", "n/a"}:
        return "unknown"
    if cleaned in ALLOWED_AUTHORS:
        return cleaned
    mapped = AUTHOR_ALIASES.get(lowered)
    if mapped:
        return mapped
    first = cleaned.split()[0]
    mapped = AUTHOR_ALIASES.get(first.lower())
    if mapped:
        return mapped
    if lowered == "other":
        return "other"
    return "other"


def build_user_prompt(path: Path, text: str) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    year = datetime.now().year
    return (
        f"Filename: {path.name}\n"
        "(The filename may itself contain a date or timestamp — use it if the "
        "document body has no clear date.)\n"
        f"Today's date: {today}. Current year: {year}. "
        f"If a date has no year, assume {year}.\n\n"
        f"Document content:\n{text}"
    )


def call_claude(
    *,
    system_prompt: str,
    user_prompt: str,
    api_key: str,
    model: str,
) -> tuple[dict[str, Any], object]:
    client = Anthropic(api_key=api_key)
    response = client.messages.create(
        model=model,
        max_tokens=MAX_OUTPUT_TOKENS,
        temperature=0.2,
        system=system_prompt,
        messages=[{"role": "user", "content": user_prompt}],
    )
    content = extract_response_text(response)
    payload = parse_json_response(content)
    return payload, response


def generate_metadata(
    relative_path: str,
    *,
    api_key: str | None = None,
    model: str | None = None,
) -> MetadataResult:
    path = resolve_file_path(relative_path)
    if not path.exists():
        raise FileNotFoundError(f"path does not exist: {path}")
    if not path.is_file():
        raise IsADirectoryError(f"path is not a file: {path}")

    text = read_file_as_text(path)
    if text is None:
        raise ValueError(f"could not read file as text: {relative_path}")

    resolved_api_key = api_key or os.getenv("ANTHROPIC_API_KEY")
    if not resolved_api_key:
        raise ValueError("ANTHROPIC_API_KEY is not set")
    resolved_model = model or os.getenv("ANTHROPIC_MODEL", DEFAULT_MODEL)

    payload, response = call_claude(
        system_prompt=SYSTEM_PROMPT,
        user_prompt=build_user_prompt(path, text),
        api_key=resolved_api_key,
        model=resolved_model,
    )

    usage = response.usage
    cost = estimate_cost(resolved_model, usage)
    created_at = resolve_entry_datetime(
        payload.get("created_at"),
        mtime=file_mtime(path),
    )

    return {
        "filename": relative_path,
        "creator": normalize_creator(payload.get("creator")),
        "created_at": created_at,
        "timestamp": datetime.now().strftime(DATETIME_FMT),
        "short summary": str(payload.get("short summary", "")).strip(),
        "full summary": str(payload.get("full summary", "")).strip(),
        "claude_stats": {
            "input_tokens": int(usage.input_tokens),
            "output_tokens": int(usage.output_tokens),
            "cost_usd": cost,
            "model": resolved_model,
        },
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate Claude metadata (creator, dates, summaries) for a single "
            "file under GOOGLE_DRIVE_BASE and print JSON."
        )
    )
    parser.add_argument(
        "relative_path",
        help="Relative path under GOOGLE_DRIVE_BASE to the file",
    )
    return parser.parse_args()


def main() -> int:
    load_dotenv()
    args = parse_args()

    try:
        result = generate_metadata(args.relative_path)
    except (ValueError, FileNotFoundError, IsADirectoryError, OSError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    except Exception as exc:
        print(f"Error: metadata generation failed: {exc}", file=sys.stderr)
        return 1

    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
