#!/usr/bin/env python3
from __future__ import annotations

import tempfile
import unittest
from datetime import datetime
from pathlib import Path

from unittest.mock import patch

from create_notes import (
    ExtractedFact,
    ProposedNote,
    build_net_new_prompt,
    collapse_facts_by_deal,
    exact_folder_matches,
    format_kinds,
    format_note_body,
    groq_near_match,
    match_hint_to_folder,
    note_filename,
    parse_extracted_facts,
    write_deal_note,
)
from fetch_all_transcripts import DealCatalogEntry
from fetch_transcripts import DealIdentity


def make_entry(
    folder_name: str,
    *,
    folder: Path | None = None,
    company_name: str | None = None,
    human_names: list[str] | None = None,
    aliases: list[str] | None = None,
) -> DealCatalogEntry:
    return DealCatalogEntry(
        folder=folder or Path(f"/tmp/deals/{folder_name}"),
        folder_name=folder_name,
        identity=DealIdentity(
            company_name=company_name,
            human_names=human_names or [],
            aliases=aliases or [],
        ),
    )


class NoteFormattingTests(unittest.TestCase):
    def test_note_filename_uses_local_timestamp(self) -> None:
        when = datetime(2026, 9, 22, 14, 5, 3)
        self.assertEqual(note_filename(when), "note_20260922_140503.txt")

    def test_format_note_body(self) -> None:
        when = datetime(2026, 9, 22, 14, 5, 3)
        body = format_note_body(
            when,
            "Tammer has decided that he will pass on Clovie.",
        )
        self.assertEqual(
            body,
            (
                "2026-09-22 14:05:03\n\n"
                "Tammer has decided that he will pass on Clovie.\n\n"
                "(This note was generated by AI.)\n"
            ),
        )

    def test_format_kinds_dedupes_preserving_order(self) -> None:
        self.assertEqual(
            format_kinds(["decision", "opinion", "decision"]),
            "decision, opinion",
        )


class DealMatchingTests(unittest.TestCase):
    def test_unique_exact_folder_name(self) -> None:
        catalog = [
            make_entry("Clovie", company_name="Clovie Inc"),
            make_entry("Mobi", company_name="Mobi"),
        ]
        match = match_hint_to_folder("Clovie", catalog)
        self.assertEqual(match.deal_folder, "Clovie")
        self.assertIn("exact name", match.reason)

    def test_unique_exact_company_name(self) -> None:
        catalog = [
            make_entry("Tony", company_name="Central Agent"),
            make_entry("Mobi", company_name="Mobi"),
        ]
        match = match_hint_to_folder("Central Agent", catalog)
        self.assertEqual(match.deal_folder, "Tony")

    def test_ambiguous_exact_company_name(self) -> None:
        catalog = [
            make_entry("Helix", company_name="Helix"),
            make_entry("HelixHealth", company_name="Helix"),
        ]
        match = match_hint_to_folder("Helix", catalog)
        self.assertIsNone(match.deal_folder)
        self.assertIn("ambiguous", match.reason)
        self.assertIn("Helix", match.reason)
        self.assertIn("HelixHealth", match.reason)
        self.assertIn("Did nothing", match.reason)

    def test_no_match(self) -> None:
        catalog = [
            make_entry("Mobi", company_name="Mobi"),
            make_entry("Clovie", company_name="Clovie"),
        ]
        match = match_hint_to_folder("UnknownCo", catalog)
        self.assertIsNone(match.deal_folder)
        self.assertIn("no deal folder found", match.reason)
        self.assertIn("Did nothing", match.reason)

    def test_unique_alias_strong_match(self) -> None:
        catalog = [
            make_entry(
                "Tony",
                company_name="TonyCo",
                aliases=["Central Agent"],
            ),
            make_entry("Mobi", company_name="Mobi"),
        ]
        match = match_hint_to_folder("Central Agent", catalog)
        self.assertEqual(match.deal_folder, "Tony")

    def test_unique_near_name_typo(self) -> None:
        catalog = [
            make_entry("Lightgrid", company_name="Lightgrid Energy"),
            make_entry("Mobi", company_name="Mobi"),
        ]
        match = match_hint_to_folder("Lightgood Energy", catalog)
        self.assertEqual(match.deal_folder, "Lightgrid")
        self.assertIn("near-name", match.reason)
        self.assertIn("Lightgood Energy", match.reason)
        self.assertIn("Lightgrid Energy", match.reason)

    def test_ambiguous_near_names_without_groq(self) -> None:
        catalog = [
            make_entry("Alpha", company_name="Helix Energy"),
            make_entry("Beta", company_name="Helix Energi"),
        ]
        match = match_hint_to_folder("Helix Energyy", catalog)
        self.assertIsNone(match.deal_folder)
        self.assertIn("ambiguous", match.reason)
        self.assertIn("Alpha", match.reason)
        self.assertIn("Beta", match.reason)

    def test_groq_near_match_accepts_unique_folder(self) -> None:
        catalog = [
            make_entry("Lightgrid", company_name="Lightgrid Energy"),
            make_entry("Mobi", company_name="Mobi"),
        ]
        with patch(
            "create_notes.groq_json_chat",
            return_value={
                "deal_folder": "Lightgrid",
                "matched_name": "Lightgrid Energy",
                "reason": "typo",
            },
        ):
            match = groq_near_match(
                "LG Energy",
                catalog,
                api_key="test",
                model="test-model",
            )
        self.assertEqual(match.deal_folder, "Lightgrid")
        self.assertIn("near-name", match.reason)

    def test_groq_near_match_null_does_nothing(self) -> None:
        catalog = [
            make_entry("Lightgrid", company_name="Lightgrid Energy"),
            make_entry("Mobi", company_name="Mobi"),
        ]
        with patch(
            "create_notes.groq_json_chat",
            return_value={
                "deal_folder": None,
                "matched_name": None,
                "reason": "no close catalog name",
            },
        ):
            match = groq_near_match(
                "UnknownCo",
                catalog,
                api_key="test",
                model="test-model",
            )
        self.assertIsNone(match.deal_folder)
        self.assertIn("no close catalog name", match.reason)

    def test_match_hint_uses_groq_when_no_difflib_hit(self) -> None:
        catalog = [
            make_entry("Lightgrid", company_name="Lightgrid Energy"),
            make_entry("Mobi", company_name="Mobi"),
        ]
        with patch(
            "create_notes.groq_json_chat",
            return_value={
                "deal_folder": "Lightgrid",
                "matched_name": "Lightgrid Energy",
                "reason": "abbreviation",
            },
        ) as mocked:
            match = match_hint_to_folder(
                "LG Energy",
                catalog,
                api_key="test",
                model="test-model",
            )
        mocked.assert_called_once()
        self.assertEqual(match.deal_folder, "Lightgrid")

    def test_empty_hint_does_nothing(self) -> None:
        catalog = [make_entry("Mobi", company_name="Mobi")]
        match = match_hint_to_folder("  ", catalog)
        self.assertIsNone(match.deal_folder)
        self.assertIn("empty company hint", match.reason)

    def test_exact_folder_matches_helper(self) -> None:
        catalog = [
            make_entry("Clovie", company_name="Clovie Inc"),
            make_entry("Mobi", company_name="Mobi"),
        ]
        matches = exact_folder_matches("clovie", catalog)
        self.assertEqual([entry.folder_name for entry in matches], ["Clovie"])


class CollapseAndWriteTests(unittest.TestCase):
    def test_collapse_one_note_per_deal(self) -> None:
        clovie = make_entry("Clovie", company_name="Clovie")
        mobi = make_entry("Mobi", company_name="Mobi")
        matched = [
            (
                ExtractedFact("Clovie", "decision", "Tammer will pass on Clovie."),
                clovie,
                "exact",
            ),
            (
                ExtractedFact("Clovie", "action", "Alex will send the pass email."),
                clovie,
                "exact",
            ),
            (
                ExtractedFact("Mobi", "opinion", "Bernie likes Mobi."),
                mobi,
                "exact",
            ),
        ]
        notes = collapse_facts_by_deal(matched)
        self.assertEqual([note.deal_folder for note in notes], ["Clovie", "Mobi"])
        self.assertEqual(notes[0].kinds, ["decision", "action"])
        self.assertIn("Tammer will pass on Clovie.", notes[0].content)
        self.assertIn("Alex will send the pass email.", notes[0].content)
        self.assertEqual(notes[1].kinds, ["opinion"])

    def test_parse_extracted_facts_skips_invalid(self) -> None:
        facts = parse_extracted_facts(
            {
                "facts": [
                    {
                        "company_hint": "Clovie",
                        "kind": "decision",
                        "content": "Tammer will pass on Clovie.",
                    },
                    {
                        "company_hint": "Mobi",
                        "kind": "gossip",
                        "content": "not a valid kind",
                    },
                    {"company_hint": "", "kind": "opinion", "content": "missing hint"},
                    "not-an-object",
                ]
            }
        )
        self.assertEqual(len(facts), 1)
        self.assertEqual(facts[0].company_hint, "Clovie")

    def test_net_new_prompt_treats_source_as_factual(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            folder = Path(tmp) / "Lightgrid"
            folder.mkdir()
            note = ProposedNote(
                deal_folder="Lightgrid",
                folder=folder,
                kinds=["opinion"],
                content="Tammer says Lightgood Energy is currently in the pipeline.",
                hints=["Lightgood Energy"],
            )
            prompt = build_net_new_prompt([note])
        self.assertIn("Treat each proposed note as factual", prompt)
        self.assertIn("Contradictions and spelling variants", prompt)
        self.assertIn("Lightgood Energy", prompt)
        self.assertIn("Name as given in the source", prompt)

    def test_dry_run_does_not_write(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            folder = Path(tmp) / "Clovie"
            folder.mkdir()
            when = datetime(2026, 9, 22, 14, 5, 3)
            filename = note_filename(when)
            body = format_note_body(
                when,
                "Tammer has decided that he will pass on Clovie.",
            )
            status = write_deal_note(folder, filename, body, dry_run=True)
            self.assertEqual(status, "would_write")
            self.assertFalse((folder / filename).exists())

            status = write_deal_note(folder, filename, body, dry_run=False)
            self.assertEqual(status, "written")
            self.assertTrue((folder / filename).exists())
            self.assertEqual((folder / filename).read_text(encoding="utf-8"), body)

            status = write_deal_note(folder, filename, body, dry_run=False)
            self.assertEqual(status, "skipped")


if __name__ == "__main__":
    unittest.main()
